/**
 * nowledge_mem_context — read today's Working Memory.
 *
 * Working Memory is Nowledge Mem's cognitive-science-grounded daily
 * artifact: focus areas, unresolved flags, recent changes, and
 * priorities — generated by the Knowledge Agent each morning and
 * updated throughout the day as events occur.
 *
 * This is fundamentally different from a static "user profile."
 * It's a living document that reflects what matters TODAY.
 */
export function createContextTool(client, logger) {
	return {
		name: "nowledge_mem_context",
		description:
			"Read or patch the user's Working Memory — today's focus areas, priorities, unresolved flags, and recent activity. " +
			"Generated by the Knowledge Agent each morning and updated throughout the day as new knowledge arrives. " +
			"READ MODE (default): Call with no parameters to understand what the user is currently focused on. " +
			"PATCH MODE: Supply patch_section to update just one section without overwriting the rest. " +
			"Use patch_content to replace the section body, or patch_append to add text to it. " +
			"Example: patch_section='## Notes', patch_append='New note: ...' to add a note without losing existing content. " +
			"Note: Working Memory is regenerated by the Knowledge Agent each morning. " +
			"To see what happened recently by date, use nowledge_mem_timeline instead.",
		parameters: {
			type: "object",
			properties: {
				patch_section: {
					type: "string",
					description:
						"Section heading to update (e.g. '## Notes', '## Focus Areas'). " +
						"Case-insensitive partial match. Required for patch mode.",
				},
				patch_content: {
					type: "string",
					description:
						"Replace the entire section body with this markdown text. Use with patch_section.",
				},
				patch_append: {
					type: "string",
					description:
						"Append this text to the section body (preserves existing content). Use with patch_section.",
				},
			},
		},
		async execute(_toolCallId, params) {
			const safeParams = params && typeof params === "object" ? params : {};
			const patchSection = safeParams.patch_section
				? String(safeParams.patch_section).trim()
				: undefined;

			// — PATCH MODE —
			if (patchSection) {
				const patchContent = safeParams.patch_content !== undefined
					? String(safeParams.patch_content)
					: undefined;
				const patchAppend = safeParams.patch_append !== undefined
					? String(safeParams.patch_append)
					: undefined;

				if (patchContent === undefined && patchAppend === undefined) {
					return {
						content: [{
							type: "text",
							text: "patch_section requires either patch_content (replace) or patch_append (append). Please provide one.",
						}],
					};
				}

				try {
					await client.patchWorkingMemory(patchSection, {
						content: patchContent,
						append: patchAppend,
					});
					const action = patchAppend !== undefined ? "Appended to" : "Replaced";
					return {
						content: [{
							type: "text",
							text: `Working Memory updated. ${action} section: "${patchSection}".`,
						}],
					};
				} catch (err) {
					const msg = err instanceof Error ? err.message : String(err);
					logger.error(`context patch failed: ${msg}`);
					return {
						content: [{
							type: "text",
							text: `Failed to patch Working Memory: ${msg}`,
						}],
					};
				}
			}

			// — READ MODE —
			try {
				const wm = await client.readWorkingMemory();

				if (!wm.available) {
					return {
						content: [
							{
								type: "text",
								text: "Working Memory not available yet. It is generated by the Knowledge Agent during the daily morning briefing. Ensure Nowledge Mem is running with Background Intelligence enabled.",
							},
						],
					};
				}

				return {
					content: [{ type: "text", text: wm.content }],
					details: { available: true },
				};
			} catch (err) {
				const msg = err instanceof Error ? err.message : String(err);
				logger.error(`context read failed: ${msg}`);
				return {
					content: [
						{
							type: "text",
							text: `Failed to read Working Memory: ${msg}`,
						},
					],
				};
			}
		},
	};
}
