/**
 * nowledge_mem_context — read startup context.
 *
 * Read mode prefers Context Bundle: owner identity, AI Identity, active
 * space, active rules, Working Memory, and KFS paths. Older nmem clients
 * fall back to Working Memory.
 *
 * Patch mode still edits Working Memory sections only.
 */
export function createContextTool(client, logger) {
	return {
		name: "nowledge_mem_context",
		description:
			"Read the user's startup context, or patch Working Memory sections. " +
			"READ MODE (default): Call with no parameters to load Context Bundle when available: owner identity, AI Identity, active space, active rules, Working Memory, and KFS paths. Older nmem clients fall back to Working Memory. " +
			"PATCH MODE: Supply patch_section to update just one section without overwriting the rest. " +
			"Use patch_content to replace the section body, or patch_append to add text to it. " +
			"Example: patch_section='## Notes', patch_append='New note: ...' to add a note without losing existing content. " +
			"Note: patch mode edits Working Memory, which is regenerated by the Knowledge Agent each morning. " +
			"To see what happened recently by date, use nowledge_mem_timeline instead.",
		parameters: {
			type: "object",
			properties: {
				patch_section: {
					type: "string",
					description:
						"Section heading to update (e.g. '## Notes', '## Focus Areas'). " +
						"Case-insensitive partial match. Required for patch mode.",
				},
				patch_content: {
					type: "string",
					description:
						"Replace the entire section body with this markdown text. Use with patch_section.",
				},
				patch_append: {
					type: "string",
					description:
						"Append this text to the section body (preserves existing content). Use with patch_section.",
				},
			},
		},
		async execute(_toolCallId, params) {
			const safeParams = params && typeof params === "object" ? params : {};
			const patchSection = safeParams.patch_section
				? String(safeParams.patch_section).trim()
				: undefined;

			// — PATCH MODE —
			if (patchSection) {
				const patchContent =
					safeParams.patch_content !== undefined
						? String(safeParams.patch_content)
						: undefined;
				const patchAppend =
					safeParams.patch_append !== undefined
						? String(safeParams.patch_append)
						: undefined;

				if (patchContent === undefined && patchAppend === undefined) {
					return {
						content: [
							{
								type: "text",
								text: "patch_section requires either patch_content (replace) or patch_append (append). Please provide one.",
							},
						],
					};
				}

				try {
					await client.patchWorkingMemory(patchSection, {
						content: patchContent,
						append: patchAppend,
					});
					const action = patchAppend !== undefined ? "Appended to" : "Replaced";
					return {
						content: [
							{
								type: "text",
								text: `Working Memory updated. ${action} section: "${patchSection}".`,
							},
						],
					};
				} catch (err) {
					const msg = err instanceof Error ? err.message : String(err);
					logger.error(`context patch failed: ${msg}`);
					return {
						content: [
							{
								type: "text",
								text: `Failed to patch Working Memory: ${msg}`,
							},
						],
					};
				}
			}

			// — READ MODE —
			try {
				const context = await client.readStartupContext();

				if (!context.available) {
					return {
						content: [
							{
								type: "text",
								text: "Startup context is not available yet. Ensure Nowledge Mem is running. Context Bundle requires a recent nmem CLI; older clients fall back to Working Memory generated by Background Intelligence.",
							},
						],
					};
				}

				return {
					content: [{ type: "text", text: context.content }],
					details: { available: true, source: context.source },
				};
			} catch (err) {
				const msg = err instanceof Error ? err.message : String(err);
				logger.error(`context read failed: ${msg}`);
				return {
					content: [
						{
							type: "text",
							text: `Failed to read startup context: ${msg}`,
						},
					],
				};
			}
		},
	};
}
