/**
 * nowledge_mem_context — read today's Working Memory.
 *
 * Working Memory is Nowledge Mem's cognitive-science-grounded daily
 * artifact: focus areas, unresolved flags, recent changes, and
 * priorities — generated by the Knowledge Agent each morning and
 * updated throughout the day as events occur.
 *
 * This is fundamentally different from a static "user profile."
 * It's a living document that reflects what matters TODAY.
 */
export function createContextTool(client, logger) {
	return {
		name: "nowledge_mem_context",
		description:
			"Read the user's Working Memory — today's focus areas, priorities, unresolved flags, and recent activity. Generated by the Knowledge Agent each morning and updated throughout the day. Call this to understand what the user is currently working on and what needs their attention.",
		parameters: {
			type: "object",
			properties: {},
		},
		async execute(_toolCallId, _params) {
			try {
				const wm = await client.readWorkingMemory();

				if (!wm.available) {
					return {
						content: [
							{
								type: "text",
								text: "Working Memory not available yet. It is generated by the Knowledge Agent during the daily morning briefing. Ensure Nowledge Mem is running with Background Intelligence enabled.",
							},
						],
					};
				}

				return {
					content: [{ type: "text", text: wm.content }],
					details: { available: true },
				};
			} catch (err) {
				const msg = err instanceof Error ? err.message : String(err);
				logger.error(`context read failed: ${msg}`);
				return {
					content: [
						{
							type: "text",
							text: `Failed to read Working Memory: ${msg}`,
						},
					],
				};
			}
		},
	};
}
